<? if($_GET['mn']==""){       
		  include("center.php");
      	}elseif($_GET['mn']=="member"){ 
          include("member.php");
    	}elseif($_GET['mn']=="viewuser"){ 
          include("viewuser.php");
	    }elseif($_GET['mn']=="editaccount"){ 
          include("editaccount.php");
	    }elseif($_GET['mn']=="edituser"){ 
          include("edituser.php");
	    }elseif($_GET['mn']=="addproduct"){ 
          include("addproduct.php");
	    }elseif($_GET['mn']=="viewproduct"){ 
          include("viewproduct.php");
	    }elseif($_GET['mn']=="editstock"){ 
          include("editstock.php");
	    }elseif($_GET['mn']=="ream"){ 
          include("ream.php");
	    }elseif($_GET['mn']=="view_orders"){ 
          include("view_orders.php");
	    }elseif($_GET['mn']=="view_orders_detail"){ 
          include("view_orders_detail.php");
	    }elseif($_GET['mn']=="view_addproduct"){ 
          include("view_addproduct.php");
	    }elseif($_GET['mn']=="view_ream"){ 
          include("view_ream.php");
	    }elseif($_GET['mn']=="view_ream_detail"){ 
          include("view_ream_detail.php");
	    }elseif($_GET['mn']=="add_order"){ 
          include("add_order.php");
	    }elseif($_GET['mn']=="report_view_user"){ 
          include("report_view_user.php");
	    }elseif($_GET['mn']=="report_view_ream"){ 
          include("report_view_ream.php");
	    }elseif($_GET['mn']=="report_view_inventory"){ 
          include("report_view_inventory.php");
	    }elseif($_GET['mn']=="report_view_addproduct"){ 
          include("report_view_addproduct.php");
	    }elseif($_GET['mn']=="report_view_row_stock"){ 
          include("report_view_row_stock.php");
	    }elseif($_GET['mn']=="view_add_order"){ 
          include("view_add_order.php");
	    }elseif($_GET['mn']=="view_add_order_detail"){ 
          include("view_add_order_detail.php");
	    }elseif($_GET['mn']=="check_add_order"){ 
          include("check_add_order.php");
	    }elseif($_GET['mn']=="save_check_add_order"){ 
          include("save_check_add_order.php");
	    }elseif($_GET['mn']=="check_order"){ 
          include("check_order.php");
	    }elseif($_GET['mn']=="edit_check_add_order"){ 
          include("edit_check_add_order.php");
	    }elseif($_GET['mn']=="report_buy_order"){ 
          include("report_buy_order.php");
	    }elseif($_GET['mn']=="receivable"){ 
          include("receivable.php");
	    }elseif($_GET['mn']=="report_ream_detail"){ 
          include("report_ream_detail.php");
	    }elseif($_GET['mn']=="save_ream_detail"){ 
          include("save_ream_detail.php");
	    }elseif($_GET['mn']=="report_add_order_detail"){ 
          include("report_add_order_detail.php");
	    }elseif($_GET['mn']=="report_view_stale"){ 
          include("report_view_stale.php");
	    }elseif($_GET['mn']=="add_supplier"){ 
          include("add_supplier.php");
	    }elseif($_GET['mn']=="division"){ 
          include("division.php");
	    }elseif($_GET['mn']=="report"){ 
          include("report.php");
	    }elseif($_GET['mn']=="unit"){ 
          include("unit.php");
	    }
		

?>
		